
- name: restart php7.0-fpm and nginx
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - php7.0-fpm
    - nginx

- name: restart postfix
  service:
    name: postfix
    state: restarted
