
- name: deploy stack and code
  hosts: web
  remote_user: victor
  become: true
  become_method: sudo
  roles:
    - common
    - postfix

- name: deploy mailhog
  hosts: mail
  remote_user: victor
  become: true
  become_method: sudo
  roles:
    - mailhog

- name: configure postfix and mailhog
  hosts: web
  remote_user: victor
  become: true
  become_method: sudo
  roles:
    - mailhog_with_postfix
