
- name: install postfix
  apt:
    name: mailutils
    state: present

- name: configure postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '(mynetworks = ).*'
    line: '\1'
    state: present
    backrefs: yes
  notify: restart postfix

- name: setup production config
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: 'recipient_delimiter = '
    line: 'recipient_delimiter = +'
    state: present
    backrefs: yes
  when: stage == "production"
  notify: restart postfix

- name: setup staging config
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: 'recipient_delimiter = '
    line: 'recipient_delimiter = *'
    state: present
    backrefs: yes
  when: stage == "staging"
  notify: restart postfix
