
- name: install postfix
  apt:
    name: mailutils
    state: present

- name: configure postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '(mynetworks = ).*'
    line: '\1'
    state: present
    backrefs: yes
  notify: restart postfix
