
- name: get gpg key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repository for docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify: enable docker autostart

- name: install docker-py
  pip:
    name: docker-py
