
- name: star mailhog
  command: "ls"
  when: mailhog == "start"

- name: stop mailhog
  command: "ls"
  when: mailhog == "stop"

  #command: "sudo docker run -d -p 8025:8025 -p 1025:1025 mailhog/mailhog"
