
- name: star mailhog
  docker_container:
    name: mailhogcontainer
    image: mailhog/mailhog
    state: started
    ports:
      - "1025:1025"
      - "8025:8025"
  when: mailhog == "start"

- name: stop mailhog
  docker_container:
    name: mailhogcontainer
    image: mailhog/mailhog
    state: stopped
  when: mailhog == "stop"

  #command: "sudo docker run -d -p 8025:8025 -p 1025:1025 mailhog/mailhog"
